apiVersion: apps/v1
kind: Deployment
metadata:
  name: enterprise-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-web
  template:
    metadata:
      labels:
        app: enterprise-web
    spec:
      containers:
        - name: web-container
          image: docker.io/placeholder/devsecops-app:latest
          ports:
            - containerPort: 80
