apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Correct field mapping to track your base files
resources:
- ../../base

# Replaces the generic container reference with your personal repository tag
images:
- name: docker.io/placeholder/devsecops-app
  newName: onkarrajput/devsecops-app
  newTag: 9e87f40280963f13be2e33932db34ec493bac46e
