apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Correct field mapping to track your base files
resources:
- ../../base

# Replaces the generic container reference with your personal repository tag
images:
- name: docker.io/placeholder/devsecops-app
  newName: onkarrajput/devsecops-app
  newTag: ca9ceed89e9bfbc5a11146ba7c1dc2eeb9e0f5d8
